### ISSUE TITLE
sjd keyboard crashing frequently

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-keyboard#7]
When using a Huawei P Smart, FIG-LX1, running Android 9, the sjd keyboard crashes all the time, like at least once pr word being written. The phone has 3 GB RAM. EMUI version 9.1.0.

Divvun Keyboard 3.1.7, version code 150919183.

The keyboard app also crashes with the following steps:
- open the app
- tap "About"
- tap the back arrow in the About screen in the app (upper left corner)
- Boom!

This is consistent and repeatable.

**Comment by albbas** [comment]
Same goes for a Motorola Edge Pro, running Android 12, with sme on 3.1.7 keyboard

**Comment by bbqsrc** [comment]
It's probably just the JNI issue Thanh and I identified this week. We're working on a fix.

**Comment by snomos** [comment]
This has been fixed with the release of Divvun Keyboards 3.2.0.
